version: '3.9'

services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: postgresCrossfitApp
    ports:
      - '5432:5432'
    volumes:
      - crossfitAppVol:/var/lib/postgresql/data
    env_file:
      - ./.env

volumes:
  crossfitAppVol:


