version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgresCrossfitApp
    ports:
      - '6501:5432'
    volumes:
      - crossfitAppVol:/data/postgres
    env_file:
      - ./.env
volumes:
  crossfitAppVol:
