import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import AuthProvider from "@/components/providers/auth-provider"
import { Toaster } from "sonner"
import { Header } from "@/components/header"
import { ThemeProvider } from "@/components/providers/theme-provider"
import { TankStackProvider } from "@/components/providers/tankStackProvider"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <div className="flex min-h-screen flex-col">
          <TankStackProvider>
            <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
              <Toaster expand={true} richColors />
              <AuthProvider>
                <Header />
                <div className="container mx-auto h-full grow">{children}</div>
              </AuthProvider>
            </ThemeProvider>
          </TankStackProvider>
        </div>
      </body>
    </html>
  )
}
